#!/bin/sh
webpack --devtool source-map

node_modules/.bin/uglifyjs dist/react-draggable.js \
  --output dist/react-draggable.min.js \
  --source-map dist/react-draggable.min.map \
  --source-map-url react-draggable.min.map \
  --in-source-map dist/react-draggable.map \
  --compress warnings=false
